### ISSUE TITLE
Sitio estatico o CMS

### ISSUE THREAD

**Issue by lasr21** [tuxlan/womoz#3]
Hay un debate si el sitio de Womoz -? womoz.mozilla-mexico.org debería ser un sitio estatico un CMS para que pueda dar de alta posts y así.

**Comment by lasr21** [comment]
Mis 2 centavos, dado que por el momento no tenemos sufieente gente que escriba en el sitio de mozilla mexico mi recomendación sería que todo los posts y contenido que se publique sea en la página de mozmx y que womoz sea un sitio de información acerca del proeycto.

**Comment by macsin** [comment]
Creo que con un CMS podemos cumplir tanto con tener la info de womoz como tener la oportunidad de publicar. En caso de que no haya muchas publicaciones entonces hay que poner la sección de posts en un nivel no tan importante y resaltar aquello que este vigente siempre. El chiste es tener una herramienta flexible, fácil de usar y fácil de actualizar. Mi humilde opinión.

**Comment by tuxlan** [comment]
En su momento se pensó estático para tener rápido el sitio, si se tenía pensado tener un CMS, pero creo que dependerá de la regularidad de publicaciones que se estén haciendo y de lo que se decida en el proyecto de Womoz y si en realidad vale la pena tener un CMS o hacer lo que comentas @lasr21

**Comment by odinm** [comment]
Aparte recuerden... El tema vital de las actualizaciones, si bien @tuxlan y yo estamos al pendiente, conlleva una administración del CMS y como dicen, ¿vale la pena por la cantidad de contenidos? Saludos,

**Comment by edgardorios** [comment]
Me parece que para el usuario final es más sencillo usar un CMS, por otra parte, es importante saber quién estaría publicando en el corto y mediano plazo, y que tanto tiempo les tomaría hacer/revisar/actualizar/etc. una publicación con o sin CMS. Si lo que se pretende es generar más contenido, creo que eso sería el valor agregado de tener un CMS. En cuanto a la administración, de momento no tengo una idea clara sobre que tipo de trabajo se tiene que hacer y/o cuanto tiempo lleva hacerlo. Saludos.

**Comment by yulireyji** [comment]
Hola! Para el sitio de WoMoz se habia pensado un CMS a futuro, dependiento de los contenidos que hubiera, cuando se hablo de los canales de difusión se opto por tener redes sociales conjunto a la comunidad en general, al igual seria bueno mantener en el blog, mi granito de arena es: hacer un landing informativo para WoMoz y que se haga la redireccion al blog de la comunidad, ese blog se podria trabajar ya seccionandolo con los proyectos que se encuentran activos.

**Comment by odinm** [comment]
@edgardorios Sobre la administración podemos llevarla sin problemas @tuxlan y un servidor, pero el punto va más hacia el contenido, que tanto generaremos como para tener un CMS, creo que de ahí podemos partir, podemos tomas dos vías, como lo habíamos pensado desde un inicio, empecemos con un sitio estático con lo que se tiene y de ahí partimos, si vemos que realmente es necesario por la gran cantidad de contenido montamos un CMS.

**Comment by macsin** [comment]
Igual un CMS puede usarse como base, para no tener que retrabajar en pasar lo que esta estático a un CMS cuando se quiera publicar más contenido. Si en un CMS se  agrega el contenido de forma que en el index quede en el nivel principal de información lo referente a la comunidad y las publicaciones tengan formato, no de blog para no preocuparnos por la temporalidad, si no de secciones informativas creo que puede funcionar desde un inicio. La cuestión que considero es que no limitemos desde un principio lo que puede ser el sitio de WoMoz, porque cuando haya la oportunidad de hacer publicaciones específicas de esta comunidad no podrá hacerse de forma inmediata, porque un sitio estático requerira meterse al código, subir a git, luego subir al servidor... cuando a través del CMS sólo tendría que iniciarse sesión y escribir la publicación fácil y rápido, sin tener que estar modificando o creando scripts por cada cosa que querramos publicar y que a la mejor dicha publicación sea temporal porque lo que no valga la pena meter código. Si como dice @odinm la administración no es un problema, entonces porque limitarse a tener un sitio estático y no un CMS en donde además puede haber más de un administrador tanto para publicar como para actualizar la plataforma.

**Comment by alexfuser** [comment]
Hola, leyendo los comentarios diré lo siguiente:
- Hay que hacer las cosas bien, no rápidas sino bien y bien planteadas. Creo que no es necesario correr sino hemos gateado y caminado antes. Debemos llevar una planeación y estrategia como si fuera un proyecto de desarrollo y pensar en el futuro lo que puede llegar a hacer, a lo que lleva el siguiente punto.
- @yulireyji menciono que habían pensando en hacerla tal vez tener un CMS para un blog en el futuro, a lo que que concuerdo con @macsin y @edgardorios sobre que no hay problema de tener desde un principio montado todo sobre un CMS, no creo que sea difícil ni complejo y los desarrollos se adaptan para un template y listo, se puede tener una landing o no, pero ya se tiene montado algo para usar.
- No creo que deberíamos poner ambas cosas en el mismo lugar. WoMoz tiene específicamente cosas que compartir y que se sientan cómodas las participantes en comentar y preguntar y saber del proyecto. Por que les preocupa quien escribiría en el blog si ahora somos casi +50 personas en la comunidad y con las acciones que empezaremos a hacer creo que igual podríamos alcanzar +15 al final del año. Las mismas personas que ya tienen tareas creo que no son las indicadas en hacer los post, sino aquellas que quieran y tengan el tiempo de hacerlo y si existen personas que lo tienen? que quieren escribir y aportar contenido para la comunidad y expresarlo? Podemos dejar el blog con notas atemporales, no tienen que ser una nota al día pero si se pueden sacar y compartir los eventos que se harán, lo que se esta trabajando dentro de la comunidad, noticias de la comunidad, comunicados, todo y específicamente todo siendo de WoMoz, cosa que se perdería dentro de Mozilla México, donde llegamos a escribir de todo en Mozilla la verdad.
- Dejemos de pensar en si nosotros lo vamos a atender, porque nosotros no siempre podremos estar, creo que para eso queremos que entren más personas y visualizar que las participaciones van desde un post hasta codear algo para mozilla. Dejemos las herramientas listas para que cuando se necesiten, se usen y no estemos corriendo a esas horas, todo porque no hubo una planeación temprana de las ideas.

Les invito a que reflexionen con la siguiente pregunta: Realmente nos cuesta el trabajo de montar un cms y tener el blog ahí para el uso de cualquier persona? 

Gracias, yo apoyo que exista un blog montado en wordpress.

**Comment by odinm** [comment]
@alexfuser Sobre el comentar si nosotros lo vamos atender va enfocado a saber con lo que se comprometerán a meter contenido, se busca que lleguen más personas, eso es un hecho y es la idea pero por el momento contemos con los que están. 

No es el tiempo que lleve instalarlo, eso esta en varios clicks, una vez instalado es necesario hacerle hardening (tarea vital y super necesaría) y si nos ponemos las pilas en 15 días se tiene el sitio. Lo digo para que podamos tener idea de cuanto tiempo nos puede llevar xD

**Comment by macsin** [comment]
@odinm el "pero" que le ponen es: "quien se compromete a meter contenido?" permitanme insistir, no es necesario que sea obligatorio el estar publicando constantemente, por eso comento que puede darse una estructura al sitio en donde no sea lo más importante el publicar periodicamente, pero que si se desea se pueda hacer sin mucho esfuerzo y sin limitaciones a unas cuantas personas. Pensar que cualquiera pueda hacerlo, cuando guste, cuando tenga tiempo, cuando se le ocurra colaborar y que no dependa del equipo de desarrollo para agregar o modificar un script que permita publicar o modificar información, pues entiendo que no tooodos somos desarrolladores y considero que debe haber apertura para que otras personas puedan exponer sus ideas o contenido que enriquezca Womoz. 
Lo anterior es porque coincido con @alexfuser en que WoMoz es, o puede ser,  lo sufientemente grande, importante e impactante como para tener su propio contenido. Por tal motivo mi "necedad" de sentar una base fácil y flexible para la publicación, para la interacción con gente que se interese en el proyecto.

Mi caso muy particular, cuando conocí a Yuli, fui a preguntarle "donde me registro?"  "donde encuentro info?" ella muy amablemente me dio su telegram, pero dije y luego? donde puedo tomar el contexto de lo que se trata Womoz? donde esta esa comundiad de Womoz (no de mozilla, de womoz) de la que ella habla? llegue al telegram y todo mundo hablando de todo y la verdad me perdi. Teniendo un portal con contenido especificamente de Womoz, puede darse ese contexto, no sólo con una misión, visión, etc. Sino teniendo una "bitacora" de eventos, participaciones, talleres, ideas, sugerencias, que muestren la vida, la historia de Womoz.

Pero si, considero que hay que empezar abriendo esa puerta para contar esa historia, que puede y debería ser contada por cualquier persona, un portal estático no da esa flexibilidad de manera inmediata, no si se trata de alguien que no sepa programar. 

En un CMS incluso pueden abrirse foros de debate para que no se mezcle lo de mozilla-mx, con lo del l10n, con lo de desarrollo, con lo de difusión, etc etc. y que quede ahí, para la historia, para la posteridad, para l@s que vienen después de nosotros jajaja (ok, ya me estoy mal viajando, pero es mi sentir acerda de este tema, ustedes disculpen :P )

**Comment by yulireyji** [comment]
Hola nuevamente! Al principio se deseaba tener un sitio de carrera ya que lo necesitabamos para lanzar el proyecto y se penso tener un landing informativo que a futuro se agregaria un blog dado a los contenidos que se maneja dentro de WoMoz, lo que se tenia planeado era esto:
- Slider con fotografías, opcional a agregar mensajes de eventos.
- Qué es WoMoz.
- Visión, Misión.
- Cómo pueds colaborar.
- Valores.
- Eventos y proyectos activos (Aquí se manejaria como blog agregando noticias, proyectos que trabajamos y eventos de los participantes).

*Contactanos (Un formulario para que los visitantes se pusieran en contacto con nosotros por si tenias dudas o deseaban participar).
- Al igual se hablo con WoMoz de Nicaragua donde propusieron para hacer la conexión entre las páginas de todo centro america y el blog de womoz global, un link que envie al telegram y un link al discourse.(Esto esta a decisión de todos)

Esas son o eran las secciones que se tienen planeadas, el diseño es completamente libre, de la guia de estilos de mozilla solo se tomaria colores y tipografía, ya que los templates que se encuentran ahí solo son ayuda si no deseas iniciar algo desde cero, dejo de ejemplo la pagina de womoz brasil https://womoz.mozillabrasil.org.br/

No se envio al area de desarrollo de la comunidad en general ya que la inciativa empezo con los participantes de WoMoz para que se generaran ideas y propuestas aunque no fueran desarrolladores (siempre necesitamos el punto de vista de diseñadores, publicistas u otras profesiones). 

No habia compartido esta información aquí ya que se me habia pasado por completo una disculpa por eso, culpa mia.

Propuesta de trabajo:
- Empezar a plantear que es lo que deseamos transmitir por medio de la página, que queremos que conozcan o vean las personas que entren a ver la página. En esta parte es donde definiriamos secciones y si es importante tener un blog o no, o se quedan las ya propuestas arriba.
- Despues de plantear las secciones de la página, realizar una propuesta gráfica, esta para ver como quedaria mejor el acomodo de los elementos dentro de la página.
- Ya que tenemos las dos anteriores, ver quienes podriamos colaborar en cada que de la página, esto para que no pase algun accidente donde alguien hizo alguna parte y otra personas la desarreglo (que no creo que se de el caso).

Como dije esto es solo una propuesta Good Vibes :D

**Comment by alexfuser** [comment]
@yulireyji te respondo lo siguiente:

"Al igual se hablo con WoMoz de Nicaragua donde propusieron para hacer la conexión entre las páginas de todo centro america y el blog de womoz global, un link que envie al telegram y un link al discourse.(Esto esta a decisión de todos)" Esto donde esta documentado? quienes hablaron con WoMoz Nicaragua? Cuando se hablo? quienes más estuvieron? porque esto no se notifica al grupo para participar dentro de esas llamadas o reuniones o charlas? 

"Esas son o eran las secciones que se tienen planeadas, el diseño es completamente libre, de la guia de estilos de mozilla solo se tomaría colores y tipografía, ya que los templates que se encuentran ahí solo son ayuda si no deseas iniciar algo desde cero, dejo de ejemplo la pagina de womoz brasil https://womoz.mozillabrasil.org.br/"    Si, sabemos que el diseño es completamente libre, como de igual forma existe una guía para los websites, pero estamos hablando de las cosas de WoMoz México, no de Brasil, donde ellos decidieron como hacer su página web, de igual forma existen muchos ejemplos de paginas de WoMoz http://womoz.mozillachile.cl/ que no sigue una landing page como brasil y así te puedo dejar muchos más links de otras comunidades que usan un diseño apegado a la guía de estilos.

"No se envio al area de desarrollo de la comunidad en general ya que la inciativa empezo con los participantes de WoMoz para que se generaran ideas y propuestas aunque no fueran desarrolladores (siempre necesitamos el punto de vista de diseñadores, publicistas u otras profesiones)."  Yo soy participante de WoMoz, y sobre todo, creo que que cada quien zapatero a su zapato. Por eso existen áreas para hacer su respectiva chamba y hacerla lo mejor posible, yo no puedo meterme en publicidad porque no lo se hacer aunque diga una opinión pero no es mi area de expertise. 

"No habia compartido esta información aquí ya que se me habia pasado por completo una disculpa por eso, culpa mia." Pues te pediría de favor que la información sea proporcionada no por partes, sino se documente y este a la vista de todos para poder tener informacion para llevar acabo las tareas dentro de los proyectos o comunidad en general.

La propuesta de trabajo se realizo la junta pasada donde se coordinaría para seguir la página web, donde en esa parte quien tomo la tarea fue @macsin la cual estaba pausada. A lo que aclaro, que es por eso que estamos haciendo la votación si es un CMS o no y nadie ha puesto ni un no o si para ello.

Las secciones de la pagina es lo de menos, se puede hacer cuando ya este la página y solo llenarlas y modificarlas en wordpress. La propuesta gráfica ya la ha presentado @macsin ayer explicando cada una de ellas de forma técnica y gráfica.

El tercer punto, eso lo sugerimos la pasada reunión y desde que indique que la pagina debería seguir la guia de estilos. @yulireyji te acercaste a @macsin si lo tengo entendido para ayudarla en la propuesta. Creo que ya se tenia un plan de trabajo hecho y se llego a un punto donde hubo las propuestas y solo se decidiría si se usaría cms o no para implementarlas, claramente, joan, elesban y los que estaban y se añadieran podrían participar.

Respecto a lo que comenta @odinm pues como venimos diciendo, el contenido podría estar ahí plasmado en el blog puede ser diario o no pero es necesario para difundirlo el trabajo de las chicas que hacen, como un historial de participación de cada una de ellas, no del trabajo total de la comunidad. 

No creo que este en 15 días, he visto lo que hiciste en la pagina de Mozilla México y quedo en menos de 4 días, creo que hay suficientes manos para hacerlo en el mínimo de tiempo posible.

Sigamos con la tarea que teníamos en la última reunión:
-Tenemos ya las propuestas que se acordaron y TODOS nosotros estábamos ahí cuando lo aceptaron quienes participarían.
-Voten con un si o no por montar el CMS para un blog en womoz
-Ya teniendo el porque del CMS o no, votando, decidiendo, implementemos las propuestas.
-Esto debe quedar para mañana, para que el el jueves mismo, @macsin y los involucrados antes y lo su que se agreguen ahora, puedan terminarla para el 11, el día que se comparta el ganador del blog y sea o la primera o segunda cosa que se presente en la página y quede listo.

PD: En las reuniones de la comunidad en general, ya se tienen formas de trabajo establecidas durante mucho tiempo, creo que el seguirlas es fácil como:
**Existe una tarea, el que la dijo la lleva a cargo, si no puede, que de chance a otra persona de terminar la tarea para el beneficio de la comunidad.** Si @macsin es la encargada ahorita de la página, que le de y termine la tarea, no veo el problema de que se haga así como en todos los proyectos lo hemos hecho.

Gracias.

**Comment by yulireyji** [comment]
Como dije si fue un error pasar los datos.
- La página web de WoMoz se creo para los participantes justamente del proyecto ya que todos estamos en el mismo canal del objetivo.
- El comentario con otros paises solo fue un comentario hecho que podemos generar una reunión para acordarlo.
- Quién decidio? Los integrantes de WoMoz no fueron la mayoria, fue el area de desarrollo donde hay personas que no estan dentro del proyecto "zapatero a sus zapatos".
- Esta excelente la propuesta de Ale, y asi como delimitamos tiempos para todo seria bueno tener tiempo para cerrar a propuestas si alguien mas desea agregar otra, si no, dejar las que ya se encuentran y trabajar en base a esas
- Tu bien lo dijiste la comunidad, WoMoz a pesar que no es ajeno a la comunidad se crearon objetivos especificos los cuales no involucran a la comunidad en general.

**Comment by alexfuser** [comment]
@yulireyji quienes estan haciendo la pagina, son integrantes de WoMoz, sobre todo, una chica quien esta haciendolo, eso le da un plus de participación.

Pues el comentario creo que debe hacerse en las reuniones o en el canal para todos decidir si lo hacemos o no.

Pues estabamos la mayoria, siendo la mayoria se acuerda, todos somos integrantes de WoMoz que estamos viendo eso y sobre todo @macsin :) y para eso las áreas, entonces para que metemos difusión y diseño a womoz, que tengan sus propias áreas, no veo el caso de duplicar areas dentro de los proyectos. Es más, tú estabas dentro del area de desarrollo y participando para la página? que te hizo cambiar de opinión de la noche a la mañana?

Esos mismos fundamentos de trabajo, no solo se llevan en la comunidad en general, se llevan en todos los proyectos donde se participan, si la organización y las reglas no se han cambiado dentro de un proyecto, este aplican a todos. Te invito a participar en más proyectos globales para que veas lo que digo.

**Comment by tonantzinmoya** [comment]
Desde mi punto de vista, lo mejor es un CMS, así tendremos la oportunidad de generar contenido y crear una mayor vinculación con las personas interesadas conforme vayamos trabajando actividades, se genera un diálogo, y esto no lo podríamos poner en un sitio general porque el enfoque es distinto. Definitivamente voto por el CMS

**Comment by macsin** [comment]
Porque no hacemos un mini hackaton presencial entre todos los interesados en crear la página y le damos termino en 24 horas o menos? :P 

Me parecen acertados los puntos de trabajo @yulireyji pero hay que ponerle fecha y responsable(s) porque si no es interminable, incluso algunas tareas pueden llevarse en paralelo. No se trata de excluir a nadie, se trata de obtener un producto, la página de Womoz, con un tiempo limite, coincido con @alexfuser en que sea poquito antes de que se tenga el logo paa presumirlo en el Portal como se debe.

A manera de ser incluyente y porque estoy de acuerdo con alfunos los puntos tratados por @alexfuser y @yulireyji , retomo lo que se ha dicho y PROPONGO lo siguiente:
- Votación para si es un CMS o es estático. Lo que podía ponerse en el grupo de womoz como encuesta de si ó no y nos quedamos con el puntaje más alto. **6 de julio**
- Enlistar las secciones que contendrá la página (puede hacerse una mini reunión para retomarlas, enlistarlas, especificar que contendrán, con obejtivos y responsables) **7 julio**
- Hacer un par de maquetas como propuesta de la distribucion del contenido y someterlas a votación de si o no. **8 de julio** (que se muestren **9 de julio** en la mañana y se vote todo el día, con la ayuda de quien guste, incluso pueden haber 3 o más o menos maquetas cada una hecha por una persona diferente y votar)
- Implementar la maqueta, trabajar en la seguridad como lo comento @odinm si es necesario, dar un día para comentarios o modificaciones. **10, 11 y 12** de julio. (con la ayuda de quienes gusten colaborar, podemos repartirnos las tareas de la implementación y si no gustan pues me la echo yo sola sólo me avisan con tiempo :P jejeje)
- Lanzar a producción ya con el logo seleccionado. **13 de julio** aunque el logo tenga que esperar dos días para ser mostrado al mundo, no perace tan mala idea :P

Son tiempos apretados pero creo que se pueden lograr pues no considero que sean tan engorrosas las tareas o como dije desde un inicio, hagamos un mini hack!!! jajaja

**Comment by elidron** [comment]
Sin afan de agredir a alguien, yo que no desempeño el cargo de developer pero si de creadora de contenidos y dentro de áreas digitales, puedo decir que es importante contar con un CMS. El blog de Womoz global tampoco tiene tanto movimiento y sería súper empático que las mujeres que pertenecemos, y las que siguen de sumarse, tengan un espacio para expresar lo que piensan sobre el proyecto.

Creo que el statemente de "al área de desarrollo no le compete hablar de Womoz" es totalmente un tema que excluye demasiado a que otros participen. Me queda claro que es súper discriminante el hecho de decir "si no estás en womoz no puedes opinar de la página y eso solo le compete a quienes nos encontramos dentro del área", no creo que sea la mejor forma de sustentar una respuesta.

Creo que todos deben de participar y que totalmente el área de desarrollo debe de encargarse de hacer el sitio web. Por otra parte, creo que algunas contestaciones están siendo autoritarias por varias de las partes y una de las cualidades de un buen líder (que en este caso no tenemos uno pero asumo que todos somos líderes de palabra) sabe delegar trabajo y ver que es lo más rápido, eficiente y funcional.

Considero que las propuestas de Ale cumplen todo lo anterior y voto porque se seleccione una, se modifiquen algunas cuestiones de distribución y listo.

Mis dos granitos como publicista digital están aquí.

**Comment by LeZelt** [comment]
Considero que un CMS es una buena opción ya que, aunque de inicio no se pueda subir tanto contenido, ya lo tendremos listo para cuando se empiece a generar contenido y eventos sobre el proyecto.

**Comment by yulireyji** [comment]
Concuerdo con Ale, propongo que se deje abierta la convocatoria para las propuestas por lo menos esta semana y votemos, y a partir de ahi empecemos a trabajar.

Good Vibes.

**Comment by odinm** [comment]
Perfecto @macsin por parte de Infraestructura comenzamos con la instalación y hardening del WP, por lo que se estarán haciendo hardenign a la base de datos y archivos del aplicativo por lo tanto únicamente lo que necesitaremos será la plantilla que se vaya a quedar, ya ustedes lo deciden, de mi parte me enfoco al server y al WP, si se tienen cambios al WP sean tan amables de pasarnos la documentación de esos cambios (archivos de WP y porque del cambio) para terminar de implementarlo en las fechas que se esta acordando y una vez listo se le pone todo el contenido. Nos adelantamos a la par de las actividades dado a que no afectamos en nada y así podemos cumplir en tiempo y forma, digo, la idea es ahorrar tiempo. La documentación para nosotros es necesaria ya que vivimos en un server compartido y tenemos que cuidad la perennidad del resto de sitios que viven ahí y que son muchos y estamos obligados a cuidar en mayor medida que lo que subimos no los afecte.

**Comment by alexfuser** [comment]
Vale, quedamos sujetos a lo indicado por @macsin

**Comment by macsin** [comment]
Va que va. Gracias @odinm te estaré compartiendo el tema que sugiero para que en base a la propuesta de maqueta que se elija se haga un tema hijo. Armaré una planeación con las tareas especificas, fechas y podrán apuntarse para participar quienes esten interesados (tipo un tablero de scrum, pero ya con tiempos). Se los comparto en un ratin.

**Comment by danysriot** [comment]
A mi también me parece chido tener un CMS para poder subir contenido, igual que a @odinm me preocupa la periodicidad para que no se vea abandonado, pero ya he visto que muchos podrían saltar para apoyar y tener algo de movimiento en el blog, lo cual está cool. 

Apoyo completamente la propuesta de @macsin con fechas de entrega y votaciones entre los que participan en el proyecto, creo que así podremos agilizar las cosas y dejar las discusiones atrás, que como ya muchos comentaron en distintos foros, solo nos hace no salir con este proyecto que está bien padre. 

Yo sí creo que es bueno el que todos participemos con propuestas e ideas, pero debe haber una persona que coordine y tome decisiones, esto de "todos deciden todo" no es funcional y nos hace dar vueltas en círculos. Seamos más flexibles y aprendamos los unos de los otros, está bien bonito que haya propuestas como las de Ale y también está cool que se hable con otros países para sacar algo en conjunto, como lo hizo @yulireyji, a veces salen cosas de forma casual que luego se comentan en el grupo, no veo necesidad de comunicar absolutamente todo lo que se hace, con los puntos más importantes y sobre todo, con los action points a realizar, es más que suficiente para que podamos darnos una idea de dónde está el proyecto y para dónde vamos. Abrazo a tod@s! 

PD. El sitio de Womoz Brasil sí está bien cool y mi propuesta favorita de las que envió Ale fue la 3 :P
